- app-datepicker.html
A few errors came up when tried to use it on safari (which needs Intl polyfill).
> Fix Intl polyfill loading

- app-datepicker.html
- demo/index.html
- test/app-datepicker-test.html
[Live Demo](https://jsbin.com/cituqeyolo/edit?html,output)
This closes #43
> feat: add support for disable dates

- app-datepicker.html
- npm-debug.log
- test/app-datepicker-test.html
> [DO NOT MERGE JUST YET] Working on crushing bugs~

- app-datepicker.html
- demo/index.html
- test/app-datepicker-test.html
Signed-off-by: motss <rong_sen.ng@zumata.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/motss/app-datepicker/83)
> :bug: Fixed locale bug on Firefox on macOS

- app-datepicker.html
- test/app-datepicker-test.html
To fix #93, #99.
Closes #94.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/motss/app-datepicker/101)
> Why polymer so broken nowadys fix

- bower.json
fixed #106 by adding dependancies on bower.json file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/motss/app-datepicker/107)
> 106 - add paper button and animation on bower json

- README.md
Hi, your component was tested and listed in our Vaadin Directory with a pretty high rating. We think it would be cool to have these badges in your project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/motss/app-datepicker/121)
> Added 5 star rating badge 🦄

- .circleci/config.yml
- package.json
- src/test/index.html
- wct.conf.json
- wct.config.ci.json
- wct.config.sl.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/motss/app-datepicker/135)
> 👷 ci: Testing

- src/app-datepicker-dialog.ts
- src/app-datepicker.ts
- src/common-styles.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/motss/app-datepicker/133)
> 🐛 src: Fix CSS variables not updating as expected

- src/app-datepicker.ts
- src/datepicker-helpers.ts
- src/test/app-datepicker-dialog/keyboards.spec.ts
- src/test/app-datepicker/keyboards.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/motss/app-datepicker/140)
> Calendar navigation with keyboard fix

- package.json
`node@8` should be the new minimum.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/motss/app-datepicker/144)
> 🔧 Update node version's requirement to fix #143

- src/app-datepicker.ts
- src/calendar.ts
- src/datepicker-helpers.ts
- src/test/app-datepicker/attributes.spec.ts
- src/test/app-datepicker/properties.spec.ts
- tsconfig.json
Calendar renders with incorrect disabled dates when different values of `firstDayOfWeek` and `disabledDays` are set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/motss/app-datepicker/145)
> Disabled days fix

- index.html
- package-lock.json
- package.json
- src/app-datepicker.ts
- src/datepicker-helpers.ts
- src/test/index.html
- src/test/runner.html
- src/tracker.ts
- tslint.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/motss/app-datepicker/148)
> chore: Cleanup

- api-references.md
- src/app-datepicker-dialog.ts
- src/app-datepicker.ts
- src/test/app-datepicker-dialog/app-datepicker-dialog.spec.ts
- src/test/app-datepicker-dialog/custom-events.spec.ts
- src/test/app-datepicker-dialog/gestures.spec.ts
- src/test/app-datepicker-dialog/keyboards.spec.ts
- src/test/app-datepicker/app-datepicker.spec.ts
- src/test/app-datepicker/custom-events.spec.ts
- src/test/app-datepicker/keyboards.spec.ts
Other changes:
* Update API references
* Minor update in custom events' detail object with defined typings
* Fix broken tests after the above changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/motss/app-datepicker/150)
> ✅ test: Add custom events tests

- .circleci/config.yml
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/motss/app-datepicker/153)
> Optimize ci

- .circleci/config.yml
- package-lock.json
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/motss/app-datepicker/158)
> Trying to upgrade axe-core

- package-lock.json
- package.json
- tsconfig.json
- tsconfig.prod.json
The changes was inspired by https://github.com/material-components/material-components-web-components/pull/439.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/motss/app-datepicker/159)
> 💥 Use `importHelpers: true` in TSConfig with `tslib`

- index.html
- package-lock.json
- package.json
- src/app-datepicker-dialog.ts
- src/app-datepicker.ts
- src/demo/properties.config.ts
To add support for dark theme.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/motss/app-datepicker/163)
> feat: Support dark theme by exposing more CSS variables for styling

- .npmrc
- README.md
- package-lock.json
- package.json
- postinstall.mjs
- postinstall.sh
- simple-git-hooks.sh
- src/tests/wdio.config.ts
1. Update dependencies
1. Minor config files
1. Drop `husky` in favor of `simple-git-hooks`
> chore: minor cleanup

- .github/FUNDING.yml
- .github/workflows/ci-helpers.yml
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- src/__tests__/date-picker-dialog/app-date-picker-dialog.test.ts
Fixes #213.
1. Remove `devDependencies` and `scripts` from `package.json` as they are not needed when installing
1. Update `publish.yml` to run steps in a more explicit manner
> fix(ci): Remove unused fields in package.json before publishing

- .github/workflows/publish.yml
- package-lock.json
- package.json
- wtr.config.mjs
1. Add `nano-staged` field in `package.json`
1. Update CI to remove `nano-staged` field before publishing
1. Update all dependencies
1. Update exports map for `moduleResolution: NodeNext`
> chore: update dependencies

- package-lock.json
- package.json
- tsconfig.json
1. Add `"useDefineForClassFields": false` in `tsconfig.json`
1. Add missing `typescript` to `devDependencies`
> fix: class fields fix
